AtheMathmo/rulinalg

src/matrix/decomposition.rs, src/matrix/mod.rs
This bidiagonal decomposition will allow us to implement a number of efficient SVD algorithms.
This PR also modifies the upper Hessenberg decomposition to consume the matrix. This is because the algorithm clones the input matrix as its first step anyway.
Finally this fixes a bug where `get_unchecked_mut` returned an `&T` instead of `&mut T`.
=> Some minor tidying and adding bidiagonal decomposition

src/matrix/mod.rs, src/matrix/slice.rs
- get_row
- get_row_mut
- get_row_unchecked
- get_row_mut_unchecked
Note:
For MatrixSlices, get_row and get_row_unchecked are implemented
directly on BaseSlice trait, as it already provides all necessary methods.
Similarly, moved get_unchecked slice implementations directly into the
trait, I don't really know but this may be a breaking change (I can revert this part if necessary).
=> implement get_row_* for Matrix, MatrixSlice and MatrixSliceMut

src/matrix/slice.rs
As discussed, I have a genuine use case for this in my cross_validate implementation.
If you think the extra complexity (in the signature at least, if not in the implementation) isn't worth it I'm happy to just replicate this internally to the cross validation module.
Sorry for the formatting changes mixed in - looks like my editor (or git?) automatically removes whitespace at the end of lines.
=> Generalise signature of select_rows and select_cols

src/matrix/mod.rs
This resolves #20 with the following changes:
- Calling `mean` on an empty matrix returns an empty matrix vector.
- Calling `variance` on a matrix with one or fewer rows/columns in the working axis returns an `Error` with kind `InvalidArg`.
=> Handle error cases for `mean` and `variance`.

src/vector.rs
This fixes #22.
Displays a vector with data `vec![a, b, c]` as `[a b c]`, and takes into account precision.
=> Implement Display trait for Vector<T>

benches/linalg/matrix.rs, src/matrix/slice.rs
Some rustfmt disagreement here but the core addition is the `swap_rows` function in the `BaseMatrixMut` trait. This function swaps the rows of a matrix or matrix slice in place without any allocation (using `mem::swap`).
Benchmarks on my system. These are 100x100 matrices.
```
test linalg::matrix::mat_swap_cols_0_99            ... bench:          60 ns/iter (+/- 1)
test linalg::matrix::mat_swap_rows_0_99            ... bench:          15 ns/iter (+/- 0)
```
=> Adding swap_rows and swap_cols for BaseMatrixMut

src/lib.rs, src/macros.rs, src/matrix/mod.rs
There is no issue for this, but I've been missing a simple macro for creating small matrices. So I wrote a very simple one. It works like this:
```
let mat = matrix!(1.0, 2.0, 3.0;
4.0, 5.0, 6.0;
7.0, 8.0, 9.0);
```
As I'm sure you can infer from the example, you delimit columns by commas and rows by semi-colons, which is also the way MATLAB does it, except I chose to make the commas compulsory. Since I'm simply converting the expression to a Rust nested array, you get compiler errors if your matrix dimensions don't match, which is an advantage compared to constructor methods (which would also need you to specify rows and cols).
Such a macro is useful not just for ourselves when testing `rulinalg`, but for users of `rulinalg` who need to create small matrices when writing tests of their …
=> Implement simple macro for matrix creation

src/convert.rs, src/vector.rs
**Motivation**:
Basically the common conveniences associated with `From` and `Into` traits, such as being able to pass `vec![…]` to `fn foo(vec: Vector<T>) { … }` instead of `Vector::new(vec![…])`.
Also it just kinda makes sense being a shallow wrapper around `Vec<T>`.
=> Added impl for From/Into<Vec<T>> to Vector<T>.

src/error.rs, src/matrix/decomposition.rs, src/matrix/mod.rs
LUP factorization will return an error whenever one of the diagonals of the U
matrix is == 0. This generally makes sense, because such a matrix is
singular and there will probably be an error down the line anyway. However, the
determinant of this matrix is known, and is 0, because the determinant is
calculated as the product of the diagonal of the triangular matrix.
I believe that it is more general to return the correct result for the
determinant (0) rather than raising an error. Let the end-user decide what to
do about this determinant of 0.
=> Return 0 from det() instead of LUP error

src/matrix/decomposition.rs, src/matrix/impl_ops.rs, src/matrix/mat_mul.rs, src/matrix/mod.rs, src/utils.rs
Motivation behind this is improved readability in source code as well as rust-docs.
It’s much quicker to spot implemented traits (`Mul<Vector<T>>`) and/or the implementing type (`Matrix<T>`) in declarations like the following:
```rust
impl<T> Mul<Vector<T>> for Matrix<T> where T: Copy + Zero + Mul<T, Output=T> + Add<T, Output=T>
```
than is it to spot them in
```rust
impl<T: Copy + Zero + Mul<T, Output=T> + Add<T, Output=T>> Mul<Vector<T>> for Matrix<T>
```
After all we’re usually reading Rust code from left to right.
Also consistency.
=> Moved bounds out of generic arguments

src/matrix/decomposition/lu.rs, src/utils.rs, tests/mat/mod.rs
This resolves issue #74 (pending approval from @bright-star ).
There was an issue with the previous pivoting - often times the pivot matrix would not actually pivot correctly (while still producing a valid orthogonal matrix and so not failing in every case). The new pivot technique works directly on the columns which may be slightly less efficient (we also remove a transpose) - but is _more_ correct.
=> Fixing LU pivot bugs

src/matrix/decomposition/lu.rs, tests/mat/mod.rs
I was having some issues with .solve; the lu decomposition failed for some simple matrices that had obvious solutions (I added the smallest one to the lu test.) It turns out that there were still lingering bugs in the pivot selection code. It didn't take into account that the optimal pivot for a given column can be changed by previous steps in the decomposition, which in some cases meant that the selected pivot was zero while other candidates were non-zero. I fixed the problem by computing the pivot matrix at the same time as the lower and upper matrices.
It seems to work, but you might want to check it just to be sure - I had to change the entire decomposition method.
=> Fixed additional lu pivot bugs

src/convert.rs, src/error.rs
Need this functionality for writing some interesting QuickCheck-based property tests for the LU Decomposition, so in the process I made an attempt to resolve #79.
As @AtheMathmo stated in the issue, the better long-term solution would be to implement `TryFrom/TryInto` once they are stabilized.
Since the functionality relies on `NumCast`, the tests only try to test a small sample of the possible conversions, and also corner cases like empty matrices. Please let me know if there are corner cases I should include!
=> Implement NumCast-based try_into

src/matrix/decomposition/svd.rs, src/matrix/deref.rs, src/matrix/impl_ops.rs, src/matrix/iter.rs, src/matrix/mod.rs, src/matrix/slice.rs
This is a very incomplete PR. I'm just putting in the request so I can track outstanding work more easily. Still to do:
There is some discussion in issue #87 . There are other ideas here which I would like to explore if I have time.
With this PR I'll try to work towards an agreeable API for these changes.
Also resolved #85 with this PR.
=> Updating get_row functions to return MatrixSlice

src/matrix/slice.rs
This PR removes the `reslice` function and closes #23 .
=> Depreciating 'reslice' function

src/vector.rs
Don't have to write ``vector.data().get_unchecked...`` to skip index boundary check.
=> API: add get_unchecked to Vector

src/matrix/decomposition/eigen.rs, src/matrix/decomposition/lu.rs, src/matrix/decomposition/svd.rs, src/matrix/mod.rs, tests/mat/mod.rs
This PR is part of our series of breaking change updates coming with 0.4.
It is bad practice to clone `self` in a function taking `&self`. This PR resolves #91 and similar situations.
=> Removing self clone on referenced functions

benches/lib.rs, benches/linalg/norm.rs, src/lib.rs, src/matrix/decomposition/eigen.rs, src/matrix/decomposition/mod.rs, src/matrix/mod.rs, src/matrix/slice.rs, src/norm/mod.rs, src/vector.rs
This PR attempts to resolve #81. New features include:
- Can define multiple norms using the `MatrixNorm` and `VectorNorm` traits.
- Automatically get the [_induced metric_ (fact 3)](https://www.math.usm.edu/perry/old_classes/mat681sp14/norm_and_metric.pdf) from the norm.
Some issues to work through:
- Should we keep a default euclidean implementation? _No_
- We have some performance hit for euclidean norm on `Matrix` - can specialize the implementation if we use a default function for this. _We will ignore this for now, but make a note for later._
- We have a set of traits each for vector and matrix types.
And some of the work left to do:
---
Here are some benchmarks (without any Lp optimizations):
```
running 12 tests
test linalg::norm::lp_1_mat_100_50                 ... bench: …
```
=> New metric traits

benches/linalg/matrix.rs, src/matrix/base/mod.rs
same impl as #115.
```
test linalg::matrix::mat_mean_cols                 ... bench:       8,800 ns/iter (+/- 200)
test linalg::matrix::mat_mean_rows                 ... bench:      18,792 ns/iter (+/- 2,265)
test linalg::matrix::mat_sum_cols                  ... bench:       4,915 ns/iter (+/- 1,770)
test linalg::matrix::mat_sum_rows                  ... bench:      12,735 ns/iter (+/- 1,606)
test linalg::matrix::mat_sum_rows_and_cols_128_100 ... bench:      27,507 ns/iter (+/- 9,377)
```
```
test linalg::matrix::mat_mean_cols                 ... bench:       9,528 ns/iter (+/- 3,713)
test linalg::matrix::mat_mean_rows                 ... bench:      15,885 ns/iter (+/- 4,485)
test linalg::matrix::mat_sum_cols                  ... bench:       4,939 ns/iter (+/- 1,895)
test …
```
=> PERF: Improve perf of matrix.sum_rows

src/convert.rs, src/macros/matrix_eq.rs, src/macros/mod.rs, src/macros/vector.rs, src/matrix/base/mod.rs, src/matrix/decomposition/eigen.rs, src/matrix/impl_mat.rs, src/matrix/impl_ops.rs, src/norm/mod.rs, src/vector.rs, tests/mat/mod.rs
We have a `matrix!` macro for ergonomic matrix declarations. Vector should have the same, imho.
=> Added `vector![…]` macro mirroring `matrix![…]`

benches/linalg/matrix.rs, src/matrix/base/mod.rs, src/matrix/slice.rs
Closes #113.
Following is benchmark results. 
```
test linalg::matrix::mat_min_col                   ... bench:      15,455 ns/iter (+/- 1,490)
test linalg::matrix::mat_min_row                   ... bench:      31,269 ns/iter (+/- 161)
```
=> Add Matrix.min / max

.gitignore
Eclipse automatically creates a file named ".project" for every single project, just like Visual Studio Code creates a ".vscode" file for workspace settings.
=> Ignore Eclipse ".project" file

src/matrix/base/mod.rs, src/matrix/decomposition/cholesky.rs, src/matrix/decomposition/eigen.rs, src/matrix/decomposition/hessenberg.rs, src/matrix/decomposition/lu.rs, src/matrix/decomposition/qr.rs, src/matrix/impl_mat.rs, src/utils.rs, src/vector/impl_vec.rs
Use ``matrix`` and ``vector`` macros in API docs.
=> DOC: use macros

src/matrix/iter.rs
It turns out that `SliceIter` does not play nice for matrices that have dimension `(k, 0)` for `k > 0`. In particular, it overflowed a `usize` because in this case it computed `0usize - 1usize`. I had to rewrite the logic a little bit in order to avoid an additional bounds check for the column (hopefully the compiler will optimize `end` as a constant instead of recomputing it every call to `next`). I also couldn't really find any tests for `iter()`, so I added some, although I'm not sure if they perhaps actually exist somewhere.
=> Fix SliceIter overflow bug in corner cases

benches/lib.rs, benches/linalg/lu.rs, benches/linalg/permutation.rs, benches/linalg/svd.rs, benches/linalg/util.rs, src/lib.rs, src/matrix/decomposition/lu.rs, src/matrix/decomposition/mod.rs, src/matrix/impl_mat.rs, src/matrix/mod.rs, src/testsupport/constraints.rs, src/testsupport/mod.rs, tests/mat/mod.rs
Currently doesn't contain any code pertaining to LU whatsoever, but rather some benchmarks for multiplication of a vector by a permutation matrix. The benchmarks are intended to compare performance between using the new `PermutationMatrix` struct and a full matrix representation of the permutation, and further motivate the use of `PermutationMatrix` in the LU decomposition. I will continue to develop the LU decomposition changes in this PR. Please see #94 for the first (unfinished) draft.
`PermutationMatrix` is implemented such that it can be applied in linear time to a vector, whereas full matrix-vector multiplication is quadratic in the size of the vector. The benchmarks support the expectation that the `PermutationMatrix` approach vastly outperforms the full matrix approach presumably …
=> LU rewrite, second draft

benches/lib.rs, benches/linalg/triangular.rs, src/matrix/mod.rs, tests/mat/mod.rs
I had some problems with these functions because they returned an error for empty matrices. In my opinion, solving a system `Ax = b` for empty `A` and `b` should merely return an empty `x`. I've had some major grievances in the past with this exact situation with Eigen, which doesn't handle this situation very well. My application generated linear systems from geometrical meshes, and sometimes these systems turned out to be "empty". Graceful handling is thus important so that users don't need to special-case these scenarios.
In any case, I took the liberty to completely rewrite the forward and backward substitution functions. I used some of the techniques I discovered when working on #150 to rewrite them in terms of the highly optimized `utils::dot` function, as well as leveraging our row …
=> Rewrite forward_substitution and back_substitution

src/matrix/base/mod.rs, src/matrix/decomposition/lu.rs, src/matrix/decomposition/mod.rs
Let me know if I should add anything, or if I need to refactor things! I didn't add a number of functions that might be useful, like `is_invertible`, `null_space`, `chosen_pivots`, `column_space`, etc.
=> Added LU decomposition with complete pivoting

benches/lib.rs, benches/linalg/cholesky.rs, src/internal_utils.rs, src/lib.rs, src/matrix/decomposition/cholesky.rs, src/matrix/decomposition/lu.rs, src/matrix/decomposition/mod.rs, tests/mat/mod.rs
I started some work on rewriting the Cholesky decomposition in the same style as LU. On the way there, I completely rewrote the algorithm using an algorithm from Golub and Van Loan, which describes the decomposition in terms of GAXPY operations. This meant that I can leverage your efficient `dot` implementation in the `utils` module. The preliminary benchmarks show a significant improvement (`cholesky_nxn` is the existing `cholesky()` implementation): 
```text
test linalg::cholesky::cholesky_100x100                                         ... bench:     201,593 ns/iter (+/- 1,126)
test linalg::cholesky::cholesky_500x500                                         ... bench:  21,765,711 ns/iter (+/- 208,204)
test linalg::cholesky::cholesky_decompose_unpack_100x100                        ... …
```
=> Cholesky decomposition rewrite: initial work

src/matrix/impl_mat.rs
This one caused me no small amount of grief until I look at the source (although the example is correct).  Ideally, it would be great to change the order of the function arguments from 'col', 'row' to 'row', 'col', but I imagine that would invisibly break a bunch of existing code (I know it would break mine).  You could potentially create a function function like `from_fn2()`, and deprecate the old one, but that's not super great either.
=> Fix for documentation on `Matrix::from_fn()`

src/norm/mod.rs
This resolves #154 with the suggested solution. I also added MatrixSlice specific tests.
Is `::matrix::Matrix<T>` acceptable or is a `use matrix::Matrix` statement desired? Felt unnecessary as it's only used 'once'.
Also, is it OK to split the matrixslice tests into their own test functions or do I want to move the slice tests into the matrix tests?
=> Fix and test metric of two MatrixSlice's (#154)

README.md
Use the `matrix!` and `assert_matrix_eq!` macros in the README examples.
Resolves #130
=> Use macros in the README examples

src/lib.rs, src/matrix/decomposition/cholesky.rs, src/matrix/decomposition/eigen.rs, src/matrix/decomposition/lu.rs, src/matrix/impl_mat.rs, src/norm/mod.rs, tests/mat/mod.rs
Changed all the easy assert!(diff < eps) to assert_scalar_eq! as I could find
There are still a few instances of a regular diff < eps that can be
found in the src/matrix/decomposition/eigen.rs, but they are inside
iterators that make it harder to easily change.
I also spruced up some of the tests, to remove unneeded clones or things of the sort and removed compiler warnings about unused 'uses'
=> Fixed (#175) and cleaned up a few tests
